version: '3.8'
services:
    cmusicai-build:
        image: cmusicai-build
        container_name: cmusicai-build
        build:
            context: .
            dockerfile: Dockerfile.build
        volumes:
            - .:/root/Cmusic
            - ./entrypoint.sh:/root/entrypoint.sh
        entrypoint: /bin/bash -c "/root/entrypoint.sh"
